Nebula Dev Merge
PersistentSS13/Nebula pull request #225
Opened 2021-07-20 01:56 UTC by NataKilar

Merges us onto latest Nebula dev. Fission is in - Praise be!

2021-07-20 19:50 UTC, PsyCommando requested changes
Looks alright. Just not sure why you removed the dna setup? Can you take a look?

2021-07-20 19:50 UTC, PsyCommando commented on mods/persistence/modules/mob/new_player.dm
> -	new_character.dna.ready_dna(new_character)
Why remove the dna setup there? It syncs dna with organs and all.

2021-07-21 19:50 UTC, PsyCommando approved these changes
Alright looks good to me now!

2021-07-21 19:51 UTC, PsyCommando approved these changes

2021-07-21 20:31 UTC, PipeWizard approved these changes
Obligatory approval comment (thanks for the review psy)

2021-07-21 21:12 UTC, merged